name: esp_provisioning_softap
description: A Flutter plugin for provisioning ESP32 modules with SoftAP
version: 1.0.3
homepage: https://github.com/nicop2000/esp_provisioning_softap
publish_to: 'none'

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^5.0.0
  cryptography: ^2.7.0
  logger: ^2.6.2
  string_validator: ^1.2.0
  http: ^1.5.0
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.petersen.nico.esp_provisioning_softap
        pluginClass: EspSoftapProvisioningPlugin
      ios:
        pluginClass: SwiftEspSoftapProvisioningPlugin